Please review my PR and suggest me if need any changes
marsiitr/Smartwatch pull request #1
Opened 2021-08-07 10:24 UTC by crooknish

2021-08-07 11:09 UTC, theobscuredev requested changes
Hey @crooknish & team, nice work!
Although make sure you do the following suggested changes before we proceed with the merging:

1. Update the README file according to the review given for the same.
2. Create separate 'Images' and 'Videos' folders inside the 'Images and Videos' directory and insert the corresponding images & videos in their respective folders. Also, try to upload the videos in .mp4 format. 
3. Remove any image/video from the 'Mechanical Design' folder. It should only contain SW or corresponding file. Insert the images in the 'Images and Videos' folder.
4. Review the Arduino code once again and remove any unnecessary line breaks, spaces and importantly any debugging statements, a few of which have been marked below.

Lemme know once you've made these changes by commenting in this thread.

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +Open Projects 2021
Apply H2 heading to this text using '## Open Projects 2021'

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +This watch can be connected to mobile via Bluetooth and it can respond to the commands given via the mobile too. It can also monitor the notifications that we receive in our mobile and alert the user
Justify the entire text using the `<p>` paragraph tag and `justify` attribute. Make sure you justify all the paragraphs separately. For eg:
`<p align="justify">`
  `<h2>Abstract</h2>`
  `<p>A Rube Goldberg Machine is .........................</p>`
`</p>`

Refer this README for the same: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +  </p>
Insert this image above your Abstract as specified in the guidelines.

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +## Electronic aspects of the design
~~Electronic aspects of the design~~ -> 'Electronic Aspect of the Design'
Make sure all the headings follow the specified convention.

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +![workflow](https://github.com/crooknish/Smartwatch/blob/de03d77899220ad73e6d6c49e93258564fbb5392/Images%20and%20Videos/Workflow.jpeg)
Mention a title for this image, what it depicts?

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +![shematic in proteus](https://github.com/crooknish/Smartwatch/blob/de03d77899220ad73e6d6c49e93258564fbb5392/Images%20and%20Videos/smartwach_proteus_simulation.JPG)
Include a title for the image.

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +For the smart watch, we made a case to protect it from external damage from scratches, any accidental drops or damage to its hardware by any means. It also makes it look good. As we are limited to wo
'Mechanical Aspect of the Design'
Also, as specified in the guidelines, include the mechanical aspect before the electronic ones.

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +The case is a 51mm x 51mm x 20mm cuboid made of PVC. It is designed such that it has it has holes for the OLED pins to be attached as well as for the keys to be placed. Also, it has base which is als
Include a line break before this statement.

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +1. 1.	One of the main limitations of the project is about the simulation environment. We didn’t have all the required features and components for simulating all the required components in a single so
Remove the extra bullet point.

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +4. Karan Saharan
Hyperlink the Github ID of each team member & your mentor (https://github.com/SanjeevKrishnan). Refer this README for the same: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +  - [solidworks](	https://www.solidworks.com/)
Update: ~~solidworks~~ -> 'SolidWorks'

2021-08-07 11:09 UTC, theobscuredev commented on README.md
> +![casing img](https://github.com/crooknish/Smartwatch/blob/3f2100be9ce8981b57f7867797f3ece374e26aba/Images%20and%20Videos/case.jpeg)
Center align the image and add a title for the same.

2021-08-07 11:09 UTC, theobscuredev commented on Images and Videos/smartwatch simulation video.md
> +Alarm simulation video drive link -- https://drive.google.com/file/d/12NadT2DNgS3l1XpdMgqY8CFpP3HzDieJ/view?usp=drivesdk
Insert a line break between these 2 statements.

2021-08-07 11:09 UTC, theobscuredev commented on src/smartwatch_arduino_nano.ino
> +#define ONE_WIRE_BUS 8
Remove unnecessary line breaks & group related things together.

2021-08-07 11:09 UTC, theobscuredev commented on src/smartwatch_arduino_nano.ino
> +  //delay(2000);
Remove such debugging statements.

2021-08-07 17:02 UTC, crooknish commented
@theobscuredev Please review the changes made and suggest if any other improvement required.

2021-08-07 18:14 UTC, theobscuredev commented
Nice work!
@SanjeevKrishnan I suggest for merge

2021-08-08 03:54 UTC, SanjeevKrishnan requested changes
A very minor change is required
Rename the "Mechanical Design" folder as "Design"

2021-08-08 04:06 UTC, crooknish commented
@SanjeevKrishnan Done the required change. You can review it once again.

2021-08-08 04:28 UTC, SanjeevKrishnan requested changes
Very few final minor changes are required!

2021-08-08 04:28 UTC, SanjeevKrishnan commented on README.md
> +  - Make the arrangement of all component according to the schematic.
Step 2 has to be rewritten. Make it "Download the proteus file from [Design/Proteus](https://github.com/crooknish/Smartwatch/tree/main/Design/Proteus)"

2021-08-08 04:28 UTC, SanjeevKrishnan commented on README.md
> +  - Copy the code kept in src folder to the arduino and compile it.
Point 3 has to be rewritten. Make it "Download the Arduino code from [src](https://github.com/crooknish/Smartwatch/tree/main/src)"

2021-08-08 04:28 UTC, SanjeevKrishnan commented on README.md
> +## How to simulate smartwatch in proteus
Steps for simulation should be numbered. Don't use bullet points.

2021-08-08 05:09 UTC, crooknish commented
@SanjeevKrishnan Made the required changes. Suggest me if any other improvement is required.

2021-08-08 05:11 UTC, SanjeevKrishnan approved these changes
Great Work Team! PR looks perfect! Merging the PR

2021-08-08 05:11 UTC, merged